# Needed and used by active fedora, to specify where to find fedora
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: /test
production:
  user: <%= ENV['FCREPO_USER'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /prod
