# Needed and used by active fedora, to specify where to find solr
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/test' %>
uat:
  url: <%= ENV['SOLR_URL'] %>
staging:
  url: <%= ENV['SOLR_URL'] %>
production:
  url: <%= ENV['SOLR_URL'] %>
