# Needed and used by active fedora, to specify where to find solr
default: &default
  url: <%= Rails.application.secrets.database_url %>
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/test' %>
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
