# Expected file format:
#    - vocabulary: ual
#      schema: http://terms.library.ualberta.ca/identifiers/
#      terms:
#        - doi
#        - path
#    - vocabulary: acl
#      schema: http://www.w3.org/ns/auth/acl
#      terms:
#        - mode
#
# Usage in the application:
#
#   VOCABULARY[:ual].doi
#   => #<RDF::Vocabulary::Term:0x3fc87891aa0c URI:http://terms.library.ualberta.ca/identifiers/doi>
#

- vocabulary: ual
  schema: http://terms.library.ualberta.ca/identifiers/
  terms:
    - depositor
    - fedora3handle
    - fedora3uuid
    - ingestbatch
    - path
    - sortyear

- vocabulary: prism
  schema: http://prismstandard.org/namespaces/basic/3.0/
  terms:
    - doi

- vocabulary: bibo
  schema: http://purl.org/ontology/bibo/
  terms:
    - status

# What about Hydra --> Samvera ???
- vocabulary: acl
  schema: 'http://projecthydra.org/ns/auth/acl#'
  terms:
    - embargoHistory
    - visibilityAfterEmbargo

- vocabulary: jupiter_core
  schema: 'http://fake.figurethisout.todo#'
  terms:
    - visibility # sharon is looking into vocabularies related to this at the moment
    - owner # not the same as depositor, potentially, as we may need to re-own works in the future while continue to record the original depositor
    - record_created_at # separate from date_created, we need to track a precise time the metadata record was created
    - community # rdf:type for community objects, which aren't merely rdf:objects but our own custom derivation
